name: Run Batch Job

on:
  schedule:
    - cron: '10 12 * * 6' # KST 21:10 on Saturday
    - cron: '0 13 * * 6'  # KST 22:00 on Saturday
  workflow_dispatch:
    inputs:
      jobName:
        description: 'Batch job name to run'
        required: false
      jobParameters:
        description: 'Job parameters'
        required: false

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    env:
      JOB_NAME: ${{ github.event.inputs.jobName || 'lottoJob' }}
      JOB_PARAMS: ${{ github.event.inputs.jobParameters || 'lotteryNo=all' }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 25 (EA)
      uses: actions/setup-java@v3
      with:
        java-version: '25-ea'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build Docker image
      run: docker build -t justone-batch .

    - name: Get start time
      id: start_time
      run: |
        echo "date=$(TZ='Asia/Seoul' date +'%Y-%m-%d %H:%M:%S KST')" >> $GITHUB_OUTPUT
        echo "ts=$(date +%s)" >> $GITHUB_OUTPUT

    - name: Run Docker and Parse Log
      id: run_and_parse
      run: |
        # Run docker, tee output to console, and capture it in a variable
        output=$(docker run justone-batch --spring.batch.job.name=${{ env.JOB_NAME }} ${{ env.JOB_PARAMS }} now=${{ steps.start_time.outputs.ts }} 2>&1)
        echo "$output"

        # Parse the captured output for the processed items count
        count=$(echo "$output" | grep 'Total items processed:' | sed -n 's/.*: //p')
        echo "insert_count=${count:-N/A}" >> $GITHUB_OUTPUT

    - name: Get end time and calculate duration
      id: end_time
      if: always()
      run: |
        end_ts=$(date +%s)
        start_ts=${{ steps.start_time.outputs.ts }}
        total_seconds=$((end_ts - start_ts))
        
        hours=$((total_seconds / 3600))
        minutes=$(((total_seconds % 3600) / 60))
        seconds=$((total_seconds % 60))
        
        echo "date=$(TZ='Asia/Seoul' date +'%Y-%m-%d %H:%M:%S KST')" >> $GITHUB_OUTPUT
        echo "duration_formatted=${hours}h ${minutes}m ${seconds}s" >> $GITHUB_OUTPUT

    - name: Send Telegram Notification
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          JustOne Batch Job Finished!

          - *Result*: ${{ job.status }}
          - *Job Name*: ${{ env.JOB_NAME }}
          - *Parameters*: ${{ env.JOB_PARAMS }}
          - *Inserted*: ${{ steps.run_and_parse.outputs.insert_count }}

          - *Start*: ${{ steps.start_time.outputs.date }}
          - *End*: ${{ steps.end_time.outputs.date }}
          - *Duration*: ${{ steps.end_time.outputs.duration_formatted }}

          See details: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      if: always()
